branch:	HACKT-00-01-04-main-00-78-11-spec-02 rev:	HACKT-00-01-04-main-00-78-11-spec-02-04
  Output format (cflat) of min_sep directive updated to
	reflect the requested feature.
  yacc stderr check done (updated a few new tests).
  distchecked, and checked against g++-4.1 -- except for a strange
	undefined reference to std::__default_allocator_template
  cleaned/committed GROUPED_DIRECTIVE_ARGUMENTS devel-switch.
  Status: almost ready to merge to trunk